import { QuartzConfig } from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"
const config: QuartzConfig = {
  configuration: {
    pageTitle: "Gracia Soberana Orizaba",
    pageTitleSuffix: " - GSO",
    enableSPA: true,
    enablePopovers: true,
    analytics: {
      provider: "plausible",
    },
    locale: "en-US",
    baseUrl: "notaspastorales.org",
    ignorePatterns: [
      ".obsidian",
      ".claude",
      ".stfolder",
      ".trash",
      "Templates",
      "Plantillas",
      "Convicciones",
      "Daily Notes",
      "Notas diarias",
      "**/*.canvas",
      "Biblioteca/02 Estudio",
      "Biblioteca/03 Reflexión",
      "Archivos/slides",
      "Archivos/slides",
      "Archivos/template",
      "Personas",
      "Claude",
      "Untitled.md",
      "Obsidian",
      "Programas y ministerios/Equipo de intercesión/Vente a 20",
      "Sermones/Compromisos de Gracia",
      "Sermones/Mensajes especiales/Matrimonio 2024a"
    ],
    defaultDateType: "modified",
    theme: {
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: {
        header: "Inter",
        body: "Noto Serif",
        code: "IBM Plex Mono",
      },
      colors: {
        lightMode: {
          light: "#FFFFFF",
          lightgray: "#E3EDF2",
          gray: "#98ACBA",
          darkgray: "#2E3D49",
          dark: "#141F25",
          secondary: "#1a7aad",
          tertiary: "#34915e",
          highlight: "rgba(34, 146, 199, 0.1)",
          textHighlight: "#fff23688",
        },
        darkMode: {
          light: "#0E161B",
          lightgray: "#141F25",
          gray: "#355464",
          darkgray: "#BDD1DB",
          dark: "#DEE8ED",
          secondary: "#4ab3e0",
          tertiary: "#39F098",
          highlight: "rgba(34, 146, 199, 0.15)",
          textHighlight: "#b3aa0288",
        },
      },
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({
        priority: ["frontmatter", "git", "filesystem"],
      }),
      Plugin.SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      Plugin.ObsidianFlavoredMarkdown({ 
        enableInHtmlEmbed: false,
        callouts: true,
        mermaid: true,
        parseTags: true,
        parseArrows: true,
        parseBlockReferences: true,
        enableYouTubeEmbed: true,
        enableVideoEmbed: true,
        enableCheckbox: false,
      }),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({ markdownLinkResolution: "shortest" }),
      Plugin.Description(),
      //Plugin.Latex({ renderEngine: "katex" }),
    ],
    filters: [Plugin.ExplicitPublish()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
       Plugin.TagPage(),
      Plugin.ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
      }),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.Favicon(),
      Plugin.NotFoundPage(),
      //Plugin.CustomOgImages(),
    ],
  },
}
export default config